apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: storage-service1
  #namespace: user1
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          ports:
            - containerPort: 8080
          env:
            - name: TARGET
              value: "I was uploaded!"

