apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: storage-event
  #namespace: user1
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    upload:
      port: "12000"
      endpoint: /upload
      method: POST

